//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherServices.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WeatherServiceSoap")]
    public interface WeatherServiceSoap {
        
        // CODEGEN: Generating message contract since element name city from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeatherByCity", ReplyAction="*")]
        WeatherServices.ServiceReference1.GetWeatherByCityResponse GetWeatherByCity(WeatherServices.ServiceReference1.GetWeatherByCityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeatherByCity", ReplyAction="*")]
        System.Threading.Tasks.Task<WeatherServices.ServiceReference1.GetWeatherByCityResponse> GetWeatherByCityAsync(WeatherServices.ServiceReference1.GetWeatherByCityRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeatherByCityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeatherByCity", Namespace="http://tempuri.org/", Order=0)]
        public WeatherServices.ServiceReference1.GetWeatherByCityRequestBody Body;
        
        public GetWeatherByCityRequest() {
        }
        
        public GetWeatherByCityRequest(WeatherServices.ServiceReference1.GetWeatherByCityRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeatherByCityRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string city;
        
        public GetWeatherByCityRequestBody() {
        }
        
        public GetWeatherByCityRequestBody(string city) {
            this.city = city;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeatherByCityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeatherByCityResponse", Namespace="http://tempuri.org/", Order=0)]
        public WeatherServices.ServiceReference1.GetWeatherByCityResponseBody Body;
        
        public GetWeatherByCityResponse() {
        }
        
        public GetWeatherByCityResponse(WeatherServices.ServiceReference1.GetWeatherByCityResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeatherByCityResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetWeatherByCityResult;
        
        public GetWeatherByCityResponseBody() {
        }
        
        public GetWeatherByCityResponseBody(string GetWeatherByCityResult) {
            this.GetWeatherByCityResult = GetWeatherByCityResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WeatherServiceSoapChannel : WeatherServices.ServiceReference1.WeatherServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeatherServiceSoapClient : System.ServiceModel.ClientBase<WeatherServices.ServiceReference1.WeatherServiceSoap>, WeatherServices.ServiceReference1.WeatherServiceSoap {
        
        public WeatherServiceSoapClient() {
        }
        
        public WeatherServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeatherServices.ServiceReference1.GetWeatherByCityResponse WeatherServices.ServiceReference1.WeatherServiceSoap.GetWeatherByCity(WeatherServices.ServiceReference1.GetWeatherByCityRequest request) {
            return base.Channel.GetWeatherByCity(request);
        }
        
        public string GetWeatherByCity(string city) {
            WeatherServices.ServiceReference1.GetWeatherByCityRequest inValue = new WeatherServices.ServiceReference1.GetWeatherByCityRequest();
            inValue.Body = new WeatherServices.ServiceReference1.GetWeatherByCityRequestBody();
            inValue.Body.city = city;
            WeatherServices.ServiceReference1.GetWeatherByCityResponse retVal = ((WeatherServices.ServiceReference1.WeatherServiceSoap)(this)).GetWeatherByCity(inValue);
            return retVal.Body.GetWeatherByCityResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WeatherServices.ServiceReference1.GetWeatherByCityResponse> WeatherServices.ServiceReference1.WeatherServiceSoap.GetWeatherByCityAsync(WeatherServices.ServiceReference1.GetWeatherByCityRequest request) {
            return base.Channel.GetWeatherByCityAsync(request);
        }
        
        public System.Threading.Tasks.Task<WeatherServices.ServiceReference1.GetWeatherByCityResponse> GetWeatherByCityAsync(string city) {
            WeatherServices.ServiceReference1.GetWeatherByCityRequest inValue = new WeatherServices.ServiceReference1.GetWeatherByCityRequest();
            inValue.Body = new WeatherServices.ServiceReference1.GetWeatherByCityRequestBody();
            inValue.Body.city = city;
            return ((WeatherServices.ServiceReference1.WeatherServiceSoap)(this)).GetWeatherByCityAsync(inValue);
        }
    }
}
